from __future__ import annotations

from dataclasses import dataclass


CATEGORIES: tuple[str, ...] = (
    "Housing",
    "Food & Dining",
    "Groceries",
    "Transportation",
    "Shopping",
    "Entertainment",
    "Subscriptions",
    "Healthcare",
    "Education",
    "Utilities",
    "Travel",
    "Personal Care",
    "Insurance",
    "Financial",
    "Income",
    "Transfer",
    "Other",
)


@dataclass(frozen=True, slots=True)
class CategoryRule:
    merchant_keywords: tuple[str, ...]
    category: str


SYSTEM_RULES: tuple[CategoryRule, ...] = (
    CategoryRule(
        merchant_keywords=(
            "swiggy",
            "zomato",
            "dominos",
            "pizza hut",
            "mcdonald",
            "kfc",
            "restaurant",
            "starbucks",
            "chipotle",
            "doordash",
            "ubereats",
            "uber eats",
            "grubhub",
            "burger king",
            "subway",
            "taco bell",
            "wendy",
            "cafe",
            "bakery",
            "diner",
            "bistro",
            "shake shack",
            "panera",
            "dunkin",
            "coffee",
            "bar & grill",
            "grill",
            "pizzeria",
            "sushi",
        ),
        category="Food & Dining",
    ),
    CategoryRule(
        merchant_keywords=(
            "bigbasket",
            "blinkit",
            "zepto",
            "dmart",
            "reliance fresh",
            "instamart",
            "whole foods",
            "trader joe",
            "safeway",
            "kroger",
            "aldi",
            "supermarket",
            "grocery",
            "costco",
            "instacart",
            "sprouts",
            "heb",
            "wegmans",
            "publix",
            "food lion",
            "meijer",
        ),
        category="Groceries",
    ),
    CategoryRule(
        merchant_keywords=(
            "netflix",
            "spotify",
            "prime video",
            "amazon prime",
            "youtube premium",
            "hotstar",
            "disney+",
            "disney",
            "apple music",
            "apple.com/bill",
            "hulu",
            "hbo",
            "max",
            "peacock",
            "paramount",
            "audible",
            "patreon",
            "substack",
            "soundcloud",
            "siriusxm",
            "chatgpt",
            "openai",
            "github",
        ),
        category="Subscriptions",
    ),
    CategoryRule(
        merchant_keywords=(
            "uber",
            "ola",
            "rapido",
            "metro",
            "irctc",
            "indigo",
            "air india",
            "lyft",
            "shell",
            "chevron",
            "bp ",
            "exxon",
            "mobil",
            "texaco",
            "gas station",
            "fuel",
            "parking",
            "toll",
            "ezpass",
            "transit",
            "train",
            "amtrak",
            "delta",
            "united air",
            "american air",
            "southwest",
            "speedway",
            "wawa",
            "circle k",
        ),
        category="Transportation",
    ),
    CategoryRule(
        merchant_keywords=(
            "amazon",
            "flipkart",
            "myntra",
            "ajio",
            "meesho",
            "target",
            "walmart",
            "best buy",
            "home depot",
            "lowes",
            "ebay",
            "ikea",
            "macys",
            "nordstrom",
            "apple store",
            "zara",
            "h&m",
            "gap",
            "sephora",
            "ulta",
            "dollar general",
        ),
        category="Shopping",
    ),
    CategoryRule(
        merchant_keywords=(
            "electricity",
            "electric",
            "power",
            "bescom",
            "tneb",
            "tangedco",
            "water bill",
            "water authority",
            "gas bill",
            "airtel",
            "jio",
            "vi ",
            "comcast",
            "xfinity",
            "verizon",
            "at&t",
            "t-mobile",
            "internet",
            "broadband",
            "spectrum",
            "coned",
            "pge",
            "pseg",
            "utility",
            "utilities",
        ),
        category="Utilities",
    ),
    CategoryRule(
        merchant_keywords=(
            "rent",
            "housing",
            "landlord",
            "mortgage",
            "lease",
            "apartment",
            "apartments",
            "hoa",
            "property management",
        ),
        category="Housing",
    ),
    CategoryRule(
        merchant_keywords=(
            "salary",
            "payroll",
            "stipend",
            "direct deposit",
            "paycheck",
            "wages",
            "bonus",
            "dividend",
        ),
        category="Income",
    ),
    CategoryRule(
        merchant_keywords=(
            "credit card payment",
            "card payment",
            "fund transfer",
            "self transfer",
            "transfer to",
            "transfer from",
            "atm",
            "withdrawal",
            "atm withdrawal",
            "venmo",
            "zelle",
            "cash app",
            "wire transfer",
            "paypal",
            "bill pay",
        ),
        category="Transfer",
    ),
    CategoryRule(
        merchant_keywords=(
            "cvs",
            "walgreens",
            "pharmacy",
            "doctor",
            "dental",
            "dentist",
            "hospital",
            "clinic",
            "medical",
            "medicine",
            "labcorp",
            "quest diagnostics",
        ),
        category="Healthcare",
    ),
    CategoryRule(
        merchant_keywords=(
            "gym",
            "fitness",
            "planet fitness",
            "equinox",
            "24 hour fitness",
            "orange theory",
            "salon",
            "barber",
            "spa",
            "haircut",
        ),
        category="Personal Care",
    ),
    CategoryRule(
        merchant_keywords=(
            "amc",
            "regal",
            "cinemark",
            "cinema",
            "theater",
            "steam",
            "playstation",
            "psn",
            "xbox",
            "nintendo",
        ),
        category="Entertainment",
    ),
)

def validate_category(category: str) -> str:
    """Validate and normalize an LLM-produced category."""
    category = category.strip()

    if category not in CATEGORIES:
        return "Other"

    return category